[project]
name = "minian-bin"
version = "0.1.0"
description = ""
authors = [
    {name = "phildong", email = ""},
]
dependencies = [
    "numpy>=2.0.0",
    "pandas>=2.2.2",
    "plotly>=5.23.0",
    "seaborn>=0.13.2",
    "xarray>=2024.7.0",
    "scipy>=1.14.1",
    "tqdm>=4.66.5",
    "opencv-python>=4.10.0.84",
    "pymetis>=2023.1.1",
    "python-levenshtein>=0.25.1",
    "dask>=2024.8.1",
    "networkx>=3.3",
    "numba>=0.60.0",
    "zarr>=2.18.2",
    "cvxpy==1.5.1",
    "ffmpeg-python>=0.2.0",
    "scikit-image>=0.24.0",
    "scikit-learn>=1.5.1",
    "statsmodels>=0.14.2",
    "distributed>=2024.8.1",
    "sparse>=0.15.4",
    "rechunker>=0.5.2",
    "natsort>=8.4.0",
]
requires-python = ">=3.11,<3.13"
readme = "README.md"
license = {text = "GPL-3.0"}

[tool.pdm.scripts]
simulate_data="python scripts/s00_simulate_data.py"
benchmark_ar="python scripts/s01_benchmark_ar.py"
benchmark_bin="python scripts/s01_benchmark_bin.py"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
